project:
  type: website
  output-dir: docs

website:
  title: "Katie Larkin"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: about.qmd
        text: About Me
      - href: research.qmd
        text: Research
      - href: cv.qmd
        text: CV

format:
  html:
    respect-user-color-scheme: true
    theme: flatly
    css: styles.css
    toc: true



